import { Plus, BookOpen, CalendarCheck, Clock3, Activity } from "lucide-react";
import { PageHeading, Button } from "../components/AppShell";
import { Stat } from "../components/Display";
import { classes } from "../data/mockSchedule";

export function CalendarPage() {
  const weekdays = ["Thứ Hai", "Thứ Ba", "Thứ Tư", "Thứ Năm", "Thứ Sáu", "Thứ Bảy", "Chủ Nhật"];
  return <><PageHeading eyebrow="THỨ HAI, 20 THÁNG 10" title="Chào bạn, Minh 👋" detail="Một tuần mới đầy năng lượng đang chờ bạn. Đây là lịch học tuần này." action={<Button icon={Plus}>Thêm lịch học</Button>} /><div className="stat-grid"><Stat label="Lớp học tuần này" value="12" note="+2 so với tuần trước" icon={BookOpen} tone="stat-blue" /><Stat label="Tổng số tín chỉ" value="18" note="Học kỳ 1 · 2025–2026" icon={CalendarCheck} tone="stat-green" /><Stat label="Tiết học tiếp theo" value="08:00" note="Cấu trúc dữ liệu · D9-301" icon={Clock3} tone="stat-amber" /><Stat label="Điểm danh" value="96%" note="Bạn đang làm rất tốt!" icon={Activity} tone="stat-purple" /></div><section className="panel calendar-panel"><div className="panel-head"><div><h2>Lịch học của tôi</h2><p>Tuần 8 · 20 – 26 tháng 10, 2025</p></div><div className="calendar-tools"><Button variant="outline">‹</Button><Button variant="outline">Hôm nay</Button><Button variant="outline">›</Button><button className="view-toggle selected">Tuần</button><button className="view-toggle">Tháng</button></div></div><div className="week-grid"><div className="time-head">GMT+7</div>{weekdays.map((day, i) => <div className={`day-head ${i === 0 ? "today" : ""}`} key={day}><span>{day}</span><b>{20 + i}</b></div>)}{["07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00"].map((time) => <div className="time-row" key={time}><span className="time-label">{time}</span>{weekdays.map((_, di) => <div className="time-cell" key={di}>{classes.filter(c => weekdays.indexOf(c.day === "T2" ? "Thứ Hai" : c.day === "T3" ? "Thứ Ba" : c.day === "T4" ? "Thứ Tư" : c.day === "T5" ? "Thứ Năm" : "Thứ Sáu") === di && Number(c.time.slice(0, 2)) === Number(time.slice(0, 2))).map(c => <article className={`class-card ${c.tone}`} key={c.code}><b>{c.name}</b><span>{c.time}</span><small>{c.room} · {c.code}</small></article>)}</div>)}</div>)}</div></section></>
}
export default CalendarPage;
