import { useEffect, useState } from "react";
import { CalendarDays, ChevronDown, CircleHelp, Code2, Database, GraduationCap, Link2, Plus, Search, ShieldCheck, Bell, ArrowUpRight, Clock3, MapPin, BookOpen, MoreHorizontal, Filter, Upload, Check, Server, Users, CalendarCheck, Activity, Pencil, Trash2, Eye } from "lucide-react";

const navItems = [
  ["calendar", "Lịch của tôi", CalendarDays], ["import", "Nhập lịch HTML", Code2],
  ["manage", "Quản lý lịch học", Database], ["admin", "Quản trị viên", ShieldCheck],
  ["settings", "Cài đặt & kết nối", Link2],
];

function Brand() { return <a className="brand" href="#/calendar"><span className="brand-mark"><CalendarDays size={21} /></span><span><b>LichHoc</b><small>Không gian học tập của bạn</small></span></a>; }

function Sidebar({ page, go }) {
  return <aside className="sidebar"><Brand /><div className="side-label">KHÔNG GIAN CỦA BẠN</div><nav className="side-nav" aria-label="Điều hướng chính">{navItems.map(([id, label, Icon]) => <a key={id} href={`#/${id}`} onClick={() => go(id)} className={`nav-link ${page === id ? "active" : ""}`}><Icon size={18} /><span>{label}</span>{id === "calendar" && <span className="nav-count">6</span>}</a>)}</nav><div className="semester-card"><div className="sem-top"><span className="live-dot" /> HỌC KỲ HIỆN TẠI</div><b>Học kỳ 1 · 2025–2026</b><span>Đại học Bách khoa Hà Nội</span><div className="semester-progress"><i /></div><small>Tuần 8 trên 15</small></div><div className="sidebar-bottom"><a className="nav-link" href="#/help"><CircleHelp size={18} />Trợ giúp & hướng dẫn</a><div className="profile-mini"><span className="avatar-initial">M</span><span><b>Nguyễn Văn Minh</b><small>K66 · Công nghệ thông tin</small></span><MoreHorizontal size={18} /></div></div></aside>
}

function Topbar({ title }) { return <header className="topbar"><div className="crumb"><GraduationCap size={18} /><span>Đại học</span><span className="crumb-slash">/</span><b>{title}</b></div><div className="top-actions"><div className="search-box"><Search size={16} /><input aria-label="Tìm kiếm" placeholder="Tìm kiếm..." /><kbd>⌘ K</kbd></div><button className="icon-button" aria-label="Thông báo"><Bell size={18} /><i /></button><span className="top-divider" /><button className="user-chip"><span className="avatar-initial">M</span><span>Minh Nguyễn</span><ChevronDown size={15} /></button></div></header> }

function PageHeading({ eyebrow, title, detail, action }) { return <div className="page-heading"><div>{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{detail && <p>{detail}</p>}</div>{action}</div> }
function Button({ children, variant = "primary", icon: Icon, ...props }) { return <button className={`button ${variant}`} {...props}>{Icon && <Icon size={16} />}{children}</button> }
function Badge({ children, tone = "blue" }) { return <span className={`badge ${tone}`}><i />{children}</span> }

const classes = [
  { day: "T2", date: "20", time: "08:00 – 09:30", name: "Cấu trúc dữ liệu và giải thuật", code: "IT3040", room: "D9-301", teacher: "Nguyễn Đức Nghĩa", tone: "blue", status: "Sắp tới" },
  { day: "T2", date: "20", time: "13:00 – 15:30", name: "Toán rời rạc", code: "MI2020", room: "B1-204", teacher: "Trần Minh Quang", tone: "mint", status: "Đã xác nhận" },
  { day: "T3", date: "21", time: "09:00 – 11:30", name: "Lập trình hướng đối tượng", code: "IT3100", room: "B1-302", teacher: "Lê Thu Hà", tone: "peach", status: "Đã xác nhận" },
  { day: "T4", date: "22", time: "07:00 – 09:30", name: "Kiến trúc máy tính", code: "IT3020", room: "D8-202", teacher: "Phạm Anh Tuấn", tone: "lavender", status: "Đã xác nhận" },
  { day: "T5", date: "23", time: "13:00 – 16:00", name: "Cơ sở dữ liệu", code: "IT3090", room: "D9-401", teacher: "Vũ Hoàng Nam", tone: "mint", status: "Đã xác nhận" },
  { day: "T6", date: "24", time: "08:00 – 10:30", name: "Xác suất thống kê", code: "MI2021", room: "B1-204", teacher: "Nguyễn Thị Lan", tone: "blue", status: "Đã xác nhận" },
];

function CalendarPage() {
  const weekdays = ["Thứ Hai", "Thứ Ba", "Thứ Tư", "Thứ Năm", "Thứ Sáu", "Thứ Bảy", "Chủ Nhật"];
  return <><PageHeading eyebrow="THỨ HAI, 20 THÁNG 10" title="Chào bạn, Minh 👋" detail="Một tuần mới đầy năng lượng đang chờ bạn. Đây là lịch học tuần này." action={<Button icon={Plus}>Thêm lịch học</Button>} /><div className="stat-grid"><Stat label="Lớp học tuần này" value="12" note="+2 so với tuần trước" icon={BookOpen} tone="stat-blue" /><Stat label="Tổng số tín chỉ" value="18" note="Học kỳ 1 · 2025–2026" icon={CalendarCheck} tone="stat-green" /><Stat label="Tiết học tiếp theo" value="08:00" note="Cấu trúc dữ liệu · D9-301" icon={Clock3} tone="stat-amber" /><Stat label="Điểm danh" value="96%" note="Bạn đang làm rất tốt!" icon={Activity} tone="stat-purple" /></div><section className="panel calendar-panel"><div className="panel-head"><div><h2>Lịch học của tôi</h2><p>Tuần 8 · 20 – 26 tháng 10, 2025</p></div><div className="calendar-tools"><Button variant="outline">‹</Button><Button variant="outline">Hôm nay</Button><Button variant="outline">›</Button><button className="view-toggle selected">Tuần</button><button className="view-toggle">Tháng</button></div></div><div className="week-grid"><div className="time-head">GMT+7</div>{weekdays.map((day, i) => <div className={`day-head ${i === 0 ? "today" : ""}`} key={day}><span>{day}</span><b>{20 + i}</b></div>)}{["07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00"].map((time, ri) => <div className="time-row" key={time}><span className="time-label">{time}</span>{weekdays.map((_, di) => <div className="time-cell" key={di}>{classes.filter(c => weekdays.indexOf(c.day === "T2" ? "Thứ Hai" : c.day === "T3" ? "Thứ Ba" : c.day === "T4" ? "Thứ Tư" : c.day === "T5" ? "Thứ Năm" : "Thứ Sáu") === di && Number(c.time.slice(0, 2)) === Number(time.slice(0, 2))).map(c => <article className={`class-card ${c.tone}`} key={c.code}><b>{c.name}</b><span>{c.time}</span><small>{c.room} · {c.code}</small></article>)}</div>)}</div>)}</div></section></>
}
function Stat({ label, value, note, icon: Icon, tone }) { return <section className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={19} /></div><span>{label}</span><b>{value}</b><small>{note}</small></section> }

function ImportPage() { return <><PageHeading eyebrow="TỰ ĐỘNG ĐỒNG BỘ" title="Nhập lịch từ cổng đào tạo" detail="Dán mã HTML thời khóa biểu để đưa lịch học của bạn vào LichHoc." /><div className="content-columns"><section className="panel import-panel"><div className="panel-head"><div><h2><Code2 size={19} /> Mã HTML thời khóa biểu</h2><p>Hỗ trợ lịch học dạng bảng hoặc RadScheduler.</p></div><Button variant="outline">Tải file HTML</Button></div><label className="field-label" htmlFor="html-input">Dán mã nguồn</label><textarea id="html-input" className="code-area" placeholder={'<!-- Dán mã HTML thời khóa biểu tại đây -->\n<table class="grid-table">\n  ...\n</table>'} /><div className="import-foot"><span>Tối đa 5 MB · HTML, HTM</span><Button icon={Upload}>Phân tích lịch</Button></div><div className="info-note"><span className="info-icon">i</span><span><b>Dữ liệu của bạn được bảo mật</b><small>HTML chỉ được sử dụng để nhận diện các buổi học và không được lưu trữ.</small></span></div></section><aside className="panel guide-panel"><div className="guide-icon"><Code2 size={21} /></div><h2>Cách lấy lịch học</h2><p>Chỉ mất khoảng 1 phút để đồng bộ thời khóa biểu của bạn.</p><ol className="steps"><li><i>1</i><span><b>Đăng nhập cổng đào tạo</b><small>Mở trang thời khóa biểu của trường bạn.</small></span></li><li><i>2</i><span><b>Mở công cụ nhà phát triển</b><small>Nhấn F12 hoặc chuột phải → Kiểm tra.</small></span></li><li><i>3</i><span><b>Sao chép mã lịch học</b><small>Chọn bảng thời khóa biểu và sao chép HTML.</small></span></li><li><i>4</i><span><b>Dán và đồng bộ</b><small>Dán mã vào khung bên trái để bắt đầu.</small></span></li></ol><a href="#/help">Xem hướng dẫn chi tiết <ArrowUpRight size={14} /></a></aside></div><section className="panel recent-panel"><div className="panel-head"><div><h2>Lần đồng bộ gần đây</h2><p>Lịch sử nhập dữ liệu từ cổng đào tạo</p></div><a href="#/manage">Xem tất cả <ArrowUpRight size={14} /></a></div><div className="recent-row"><span className="recent-check"><Check size={16} /></span><span><b>Thời khóa biểu học kỳ 1</b><small>Hệ thống quản lý đào tạo · 18/10/2025 lúc 14:32</small></span><Badge tone="green">Thành công</Badge><span className="recent-count">12 lớp học</span></div></section></> }

function ManagePage() { return <><PageHeading eyebrow="DANH SÁCH HỌC PHẦN" title="Quản lý lịch học" detail="Theo dõi, sắp xếp và cập nhật các lớp học trong học kỳ của bạn." action={<Button icon={Plus}>Thêm môn học</Button>} /><div className="stat-grid compact-stats"><Stat label="Tổng số lớp" value="6" note="Trong học kỳ hiện tại" icon={BookOpen} tone="stat-blue" /><Stat label="Tín chỉ đăng ký" value="18" note="Trên tổng 24 tín chỉ" icon={CalendarCheck} tone="stat-green" /><Stat label="Buổi học sắp tới" value="12" note="Trong 7 ngày tiếp theo" icon={Clock3} tone="stat-amber" /></div><section className="panel table-panel"><div className="table-toolbar"><div className="search-box table-search"><Search size={16} /><input placeholder="Tìm theo môn học, giảng viên, phòng..." /></div><Button variant="outline" icon={Filter}>Bộ lọc</Button><select aria-label="Học kỳ"><option>Học kỳ 1 · 2025–2026</option></select><Button variant="outline" icon={Upload}>Xuất dữ liệu</Button></div><div className="table-scroll"><table><thead><tr><th>MÔN HỌC</th><th>MÃ LỚP</th><th>LỊCH HỌC</th><th>PHÒNG</th><th>GIẢNG VIÊN</th><th>TRẠNG THÁI</th><th></th></tr></thead><tbody>{classes.map((c, i) => <tr key={c.code}><td><div className="course-cell"><i className={`course-mark ${c.tone}`} /><span><b>{c.name}</b><small>{[3, 3, 3, 3, 4, 2][i]} tín chỉ</small></span></div></td><td><span className="code-pill">{c.code}</span></td><td>{c.day} · {c.time}</td><td><MapPin size={14} />{c.room}</td><td>{c.teacher}</td><td><Badge tone={i === 0 ? "amber" : "green"}>{c.status}</Badge></td><td><div className="row-actions"><button aria-label="Xem"><Eye size={16} /></button><button aria-label="Sửa"><Pencil size={16} /></button><button aria-label="Xóa"><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div><div className="table-footer">Hiển thị <b>1–6</b> trong <b>6</b> lớp học <div><button>‹</button><button className="current-page">1</button><button>›</button></div></div></section></> }

function AdminPage() { return <><PageHeading eyebrow="TỔNG QUAN HỆ THỐNG" title="Bảng điều khiển quản trị" detail="Theo dõi hoạt động và tình trạng hệ thống LichHoc." action={<Button variant="outline">24 giờ qua <ChevronDown size={15} /></Button>} /><div className="stat-grid"><Stat label="Tổng người dùng" value="2,486" note="↑ 12.8% so với tháng trước" icon={Users} tone="stat-blue" /><Stat label="Lịch học được tạo" value="18,392" note="↑ 8.2% so với tháng trước" icon={CalendarDays} tone="stat-green" /><Stat label="Lượt đồng bộ hôm nay" value="1,204" note="↑ 4.6% so với hôm qua" icon={Activity} tone="stat-amber" /><Stat label="Tình trạng hệ thống" value="99.9%" note="Tất cả dịch vụ đang hoạt động" icon={Server} tone="stat-purple" /></div><div className="admin-grid"><section className="panel chart-panel"><div className="panel-head"><div><h2>Hoạt động người dùng</h2><p>Lượt truy cập trong 7 ngày gần nhất</p></div><Badge tone="green">+12.8%</Badge></div><div className="chart-legend"><i /> Lượt truy cập <i className="legend-secondary" /> Người dùng mới</div><div className="chart"><div className="chart-y"><span>2.000</span><span>1.500</span><span>1.000</span><span>500</span><span>0</span></div><div className="chart-bars">{[42, 55, 48, 74, 61, 88, 68].map((h, i) => <div className="bar-pair" key={i}><i style={{ height: `${h}%` }} /><b style={{ height: `${Math.max(h - 18, 14)}%` }} /><small>{["T2", "T3", "T4", "T5", "T6", "T7", "CN"][i]}</small></div>)}</div></div></section><section className="panel service-panel"><div className="panel-head"><div><h2>Dịch vụ hệ thống</h2><p>Trạng thái hiện tại</p></div><Badge tone="green">Hoạt động</Badge></div>{[["API Flask", "Xử lý và phân tích lịch", "24 ms"], ["Express API", "Quản lý dữ liệu lịch học", "18 ms"], ["MongoDB", "Cơ sở dữ liệu", "12 ms"], ["Đồng bộ thời khóa biểu", "Tác vụ nhập lịch", "Đang chạy"]].map(([name, sub, val]) => <div className="service-row" key={name}><span className="service-dot" /><span><b>{name}</b><small>{sub}</small></span><span className="service-value">{val}</span></div>)}</section></div><section className="panel recent-panel"><div className="panel-head"><div><h2>Người dùng mới</h2><p>Tài khoản đăng ký gần đây</p></div><a href="#/admin">Xem tất cả <ArrowUpRight size={14} /></a></div><div className="user-list">{[["Trần Hà My", "hamy@sv.university.edu", "K68 · Khoa Kinh tế"], ["Lê Quang Huy", "huy.le@sv.university.edu", "K67 · Khoa Điện tử"], ["Phạm Ngọc Anh", "anh.pham@sv.university.edu", "K66 · Khoa CNTT"]].map(([name, email, course]) => <div className="admin-user" key={email}><div className="initials">{name.split(" ").slice(-1)[0].slice(0, 1)}</div><span><b>{name}</b><small>{email}</small></span><span className="user-course">{course}</span><Badge tone="green">Đang hoạt động</Badge></div>)}</div></section></> }

function SettingsPage() { return <><PageHeading eyebrow="TÙY CHỈNH KHÔNG GIAN" title="Cài đặt & kết nối" detail="Quản lý tài khoản, tùy chọn lịch và các kết nối của bạn." /><div className="settings-layout"><nav className="settings-nav"><a className="chosen"><Users size={17} />Tài khoản</a><a><CalendarDays size={17} />Tùy chọn lịch</a><a><Bell size={17} />Thông báo</a><a><Link2 size={17} />Kết nối</a></nav><div className="settings-content"><section className="panel settings-panel"><div className="settings-title"><div><h2>Thông tin cá nhân</h2><p>Cập nhật thông tin hiển thị trên hồ sơ của bạn.</p></div><Button variant="outline">Chỉnh sửa</Button></div><div className="avatar-edit"><span className="avatar-large">M</span><span><b>Ảnh đại diện</b><small>JPG, PNG · tối đa 2 MB</small></span><Button variant="outline">Thay ảnh</Button></div><div className="form-grid"><Field label="Họ và tên" value="Nguyễn Văn Minh" /><Field label="Email sinh viên" value="minh.nguyen@sv.university.edu" /><Field label="Mã sinh viên" value="2022001234" /><Field label="Khoa" value="Công nghệ thông tin" /></div></section><section className="panel settings-panel"><div className="settings-title"><div><h2>Tích hợp hệ thống</h2><p>Kết nối với cổng đào tạo và các dịch vụ hỗ trợ.</p></div><Badge tone="green">2 kết nối</Badge></div>{[["Cổng đào tạo", "Đồng bộ thời khóa biểu tự động", "Đã kết nối", "blue"], ["Google Calendar", "Xuất lịch sang lịch cá nhân", "Chưa kết nối", "gray"]].map(([name, desc, state, tone]) => <div className="integration-row" key={name}><div className={`integration-icon ${tone}`}>{name.startsWith("Cổng") ? <GraduationCap size={20} /> : <CalendarDays size={20} />}</div><span><b>{name}</b><small>{desc}</small></span><Badge tone={state.startsWith("Đã") ? "green" : "gray"}>{state}</Badge><Button variant="outline">{state.startsWith("Đã") ? "Quản lý" : "Kết nối"}</Button></div>)}</section></div></div></> }
function Field({ label, value }) { return <label className="field"><span>{label}</span><input defaultValue={value} /></label> }

function LandingPage({ go }) { return <main className="landing"><header><Brand /><nav><a href="#features">Tính năng</a><a href="#about">Giới thiệu</a><a href="#help">Trợ giúp</a></nav><div><a className="login-link" href="#/login">Đăng nhập</a><Button onClick={() => go("register")}>Bắt đầu miễn phí <ArrowUpRight size={15} /></Button></div></header><section className="landing-hero"><div className="hero-copy"><Badge tone="blue">✦ DÀNH CHO SINH VIÊN HIỆN ĐẠI</Badge><h1>Giải phóng thời gian khỏi <em>thời khóa biểu</em> phức tạp.</h1><p>Tập trung vào điều quan trọng nhất. LichHoc giúp bạn sắp xếp lịch học, quản lý môn học và làm chủ từng tuần trong học kỳ.</p><div className="hero-actions"><Button onClick={() => go("register")}>Tạo tài khoản miễn phí <ArrowUpRight size={16} /></Button><a href="#features" className="text-action">Khám phá LichHoc <span>→</span></a></div><div className="trust-row"><div className="avatar-stack"><span>M</span><span>H</span><span>M</span><span>+</span></div><span><b>2.400+</b> sinh viên đang sử dụng</span></div></div><div className="hero-visual"><div className="hero-orbit" /><div className="hero-schedule"><div className="mock-top"><div><span className="eyebrow">HỌC KỲ 1 · 2025–2026</span><h3>Lịch học tuần này</h3></div><span className="mock-avatar">M</span></div><div className="mock-week">{["T2", "T3", "T4", "T5", "T6"].map((day, i) => <span key={day} className={i === 1 ? "selected" : ""}>{day}<b>{20 + i}</b></span>)}</div><div className="mock-event blue"><i /> <span><b>Cấu trúc dữ liệu</b><small>08:00 – 09:30 · D9-301</small></span></div><div className="mock-event green"><i /> <span><b>Lập trình hướng đối tượng</b><small>10:00 – 11:30 · B1-302</small></span></div><div className="mock-event amber"><i /> <span><b>Toán rời rạc</b><small>13:00 – 15:30 · B1-204</small></span></div><div className="mock-sync"><span><Check size={14} /> Lịch học đã được đồng bộ</span><span>vừa xong</span></div></div><div className="floating-note"><span className="floating-check"><Check size={15} /></span><span><b>Tuần học của bạn</b><small>Đã sẵn sàng ✨</small></span></div><div className="floating-date"><CalendarDays size={18} /><span><b>20</b><small>THÁNG 10</small></span></div></div></section><section id="features" className="landing-features"><div><div className="eyebrow">HỌC TẬP NHẸ NHÀNG HƠN</div><h2>Mọi thứ bạn cần để làm chủ lịch học.</h2></div><div className="feature-row">{[[CalendarDays, "Một lịch học rõ ràng", "Xem toàn bộ tuần học trong một giao diện trực quan."], [Code2, "Đồng bộ dễ dàng", "Nhập lịch học từ cổng đào tạo chỉ với vài thao tác."], [Clock3, "Luôn đúng nhịp", "Biết buổi học tiếp theo và thời gian dành cho bạn."]].map(([I, t, d]) => <article className="feature-card" key={t}><span><I size={20} /></span><h3>{t}</h3><p>{d}</p></article>)}</div></section><footer>© 2025 LichHoc · Thiết kế cho hành trình học tập của bạn</footer></main> }

function AuthPage({ mode, go }) { const register = mode === "register"; return <main className="auth-layout"><section className="auth-art"><Brand /><div className="auth-message"><Badge tone="blue">✦ HỌC TẬP CHỦ ĐỘNG</Badge><h1>Mỗi tuần học,<br />một nhịp điệu <em>của riêng bạn.</em></h1><p>Sắp xếp thời gian thông minh. Tận hưởng hành trình đại học trọn vẹn hơn.</p><div className="auth-preview"><div><CalendarDays size={18} /><b>Thứ Hai, 20 tháng 10</b></div><span>08:00　Cấu trúc dữ liệu</span><span>13:00　Toán rời rạc</span></div></div><small className="auth-copyright">© 2025 LichHoc · Đồng hành cùng bạn trên giảng đường.</small></section><section className="auth-form-side"><a className="back-home" href="#/home">← Trang chủ</a><div className="auth-form"><div className="eyebrow">{register ? "BẮT ĐẦU HÀNH TRÌNH" : "CHÀO MỪNG TRỞ LẠI"}</div><h2>{register ? "Tạo tài khoản" : "Đăng nhập"}</h2><p>{register ? "Tạo không gian học tập của riêng bạn." : "Đăng nhập để xem lịch học của bạn."}</p>{register && <Field label="Họ và tên" value="" />}<Field label="Email sinh viên" value="" /><label className="field"><span>Mật khẩu</span><input type="password" placeholder="Nhập mật khẩu" /></label>{register && <label className="field"><span>Nhập lại mật khẩu</span><input type="password" placeholder="Nhập lại mật khẩu" /></label>}{!register && <div className="auth-options"><label><input type="checkbox" /> Ghi nhớ đăng nhập</label><a href="#/login">Quên mật khẩu?</a></div>}<Button>{register ? "Tạo tài khoản miễn phí" : "Đăng nhập"} <ArrowUpRight size={16} /></Button><div className="auth-switch">{register ? "Đã có tài khoản?" : "Chưa có tài khoản?"} <a href={`#/${register ? "login" : "register"}`} onClick={() => go(register ? "login" : "register")}>{register ? "Đăng nhập" : "Đăng ký miễn phí"}</a></div><div className="auth-terms">Bằng cách tiếp tục, bạn đồng ý với <a href="#terms">Điều khoản sử dụng</a> và <a href="#privacy">Chính sách bảo mật</a>.</div></div></section></main> }

function App() { const readPage = () => location.hash.replace(/^#\/?/, "") || "calendar"; const [page, setPage] = useState(readPage); useEffect(() => { const onHash = () => setPage(readPage()); window.addEventListener("hashchange", onHash); return () => window.removeEventListener("hashchange", onHash) }, []); const go = (next) => { location.hash = `/${next}`; setPage(next) }; if (page === "home" || page === "") return <LandingPage go={go} />; if (page === "login" || page === "register") return <AuthPage mode={page} go={go} />; const title = navItems.find(([id]) => id === page)?.[1] || "Lịch của tôi"; let content = page === "import" ? <ImportPage /> : page === "manage" ? <ManagePage /> : page === "admin" ? <AdminPage /> : page === "settings" ? <SettingsPage /> : <CalendarPage />; return <div className="app-shell"><Sidebar page={page} go={go} /><div className="main-column"><Topbar title={title} /><main className="page-content">{content}<footer className="app-footer"><span>© 2025 LichHoc</span><span>Học tập có kế hoạch. Sống trọn từng ngày.</span><a href="#/help">Trung tâm trợ giúp</a></footer></main></div></div> }
export default App;
